name: Workflow Teste

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # Roda GitHub action pré-existente
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore github4women/github4women.csproj

    - name: Build project
      run: dotnet build github4women/github4women.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test github4women/github4women.csproj --no-restore --verbosity normal

    #Roda um script custom
    - name: Custom script example
      run: |
        echo "Executing custom script"